### ISSUE TITLE
After running for a period of time, operator will print some unexpected message

### ISSUE THREAD

**Issue by cdmikechen** [quarkiverse/quarkus-operator-sdk#134]
I've run `quarkus-operator` by a native image in okd4.7 for some time. At first, it worked normally when pod started. But after a period of time, it began to appear the following messages :
```
2021-10-24 15:12:42,883 INFO  [io.jav.ope.pro.eve.int.CustomResourceEventSource] (OkHttp https://172.30.0.1/...) Closing watch 'dagcontroller' Controller -> io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@988f69b
2021-10-24 15:12:42,883 INFO  [io.jav.ope.pro.eve.int.CustomResourceEventSource] (OkHttp https://172.30.0.1/...) Closing watch 'dagcontroller' Controller -> io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@3ba7a177
2021-10-24 16:13:32,440 WARN  [io.jav.ope.pro.eve.int.CustomResourceEventSource] (OkHttp https://172.30.0.1/...) Received error for watch, will try to reconnect.: io.fabric8.kubernetes.client.WatcherException: too old resource version: 227558973 (229589125)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onStatus(AbstractWatchManager.java:273)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:257)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 227558973 (229589125)
	... 15 more

2021-10-24 16:13:32,441 INFO  [io.jav.ope.pro.eve.int.CustomResourceEventSource] (OkHttp https://172.30.0.1/...) Closing watch 'dagcontroller' Controller -> io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@988f69b
2021-10-24 16:13:32,441 INFO  [io.jav.ope.pro.eve.int.CustomResourceEventSource] (OkHttp https://172.30.0.1/...) Closing watch 'dagcontroller' Controller -> io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@3ba7a177
2021-10-24 16:13:32,441 INFO  [io.jav.ope.pro.eve.int.CustomResourceEventSource] (OkHttp https://172.30.0.1/...) Closing watch 'dagcontroller' Controller -> io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@3e0e8853
2021-10-24 17:22:12,040 WARN  [io.jav.ope.pro.eve.int.CustomResourceEventSource] (OkHttp https://172.30.0.1/...) Received error for watch, will try to reconnect.: io.fabric8.kubernetes.client.WatcherException: too old resource version: 218903201 (229589125)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onStatus(AbstractWatchManager.java:273)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:257)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 218903201 (229589125)
	... 15 more
```
I don't know what caused it for the time being, and this error will cause the new resource to be unrecognized.

**Comment by cdmikechen** [comment]
@metacosm 
I would like to ask when 2.0.0 will support this patch?

**Comment by metacosm** [comment]
@cdmikechen 2.0.0 has been released with this fix last week. I somehow forgot to publish the release on GitHub… 😓
