### ISSUE TITLE
NPE on build if Reconciler parameterized by io.fabric8.istio.api.networking.v1beta1.Gateway

### ISSUE THREAD

**Issue by foal** [quarkiverse/quarkus-operator-sdk#195]
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.6.2.Final:build (default) on project istio-cert-manager-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed
 due to errors
[ERROR]         [error]: Build step io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor#createConfigurationServiceAndOperator threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.superName()"
 because "info" is null
[ERROR]         at io.quarkus.deployment.util.JandexUtil.isSubclassOf(JandexUtil.java:326)
[ERROR]         at io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor.createControllerConfiguration(OperatorSDKProcessor.java:266)
[ERROR]         at io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor.lambda$createConfigurationServiceAndOperator$0(OperatorSDKProcessor.java:150)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[ERROR]         at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1689)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[ERROR]         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[ERROR]         at io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor.createConfigurationServiceAndOperator(OperatorSDKProcessor.java:154)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

**Comment by metacosm** [comment]
Which version of the extension are you using?

**Comment by foal** [comment]
```
                <quarkus.platform.version>2.6.2.Final</quarkus.platform.version>
		<quarkus-operator-sdk.version>3.0.0</quarkus-operator-sdk.version>
		<operator-framework-core.version>2.0.1</operator-framework-core.version>
		<kubernetes-client.version>5.11.2</kubernetes-client.version>
```

**Comment by foal** [comment]
BTW: https://github.com/foal/k8s-operator-istio-cert

**Comment by metacosm** [comment]
The issue occurs because the Istio model is not indexed by Jandex. Not sure it should be, though. Working to see if we can do without.

**Comment by metacosm** [comment]
Can you give #196 a try? It should fix your issue.

**Comment by foal** [comment]
Look like the issue is fixed with #196, but I faced up in missing `version.properties` issue. Is it documented somewhere?
```
[WARNING] [io.quarkiverse.operatorsdk.runtime.Version] Couldn't find version.properties file. Default version information will be used.
[WARNING] [io.quarkus.kubernetes.deployment.KubernetesDeployer] An openshift deployment was requested, but the container image group:foal is not aligned with the currently selected project:istio-system.it is strongly advised to align them, or else the image might not be reachable.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.982 s
[INFO] Finished at: 2022-01-19T08:29:41+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.6.1.Final:build (default) on project istio-cert-manager-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor#createConfigurationServiceAndOperator threw an exception: java.lang.NullPointerException: Cannot invoke "String.length()" because "text" is null[ERROR]         at java.base/java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1474)
[ERROR]         at java.base/java.text.DateFormat.parse(DateFormat.java:397)
[ERROR]         at io.quarkiverse.operatorsdk.runtime.Version.loadFromProperties(Version.java:67)
[ERROR]         at io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor.createConfigurationServiceAndOperator(OperatorSDKProcessor.java:178)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

**Comment by foal** [comment]
Next error - 
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.6.2.Final:build (default) on project istio-cert-manager-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor#addRBACForCustomResources threw an exception: java.lang.ClassCastException: class io.fabric8.istio.api.networking.v1beta1.Gateway cannot be cast to class io.fabric8.kubernetes.client.CustomResource (io.fabric8.istio.api.networking.v1beta1.Gateway and io.fabric8.kubernetes.client.CustomResource are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @3151277f)
[ERROR]         at io.fabric8.crd.generator.CustomResourceInfo.fromClass(CustomResourceInfo.java:133)
[ERROR]         at io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor.lambda$addRBACForCustomResources$2(OperatorSDKProcessor.java:205)
[ERROR]         at java.base/java.util.HashMap.forEach(HashMap.java:1420)
[ERROR]         at io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor.addRBACForCustomResources(OperatorSDKProcessor.java:203)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

**Comment by metacosm** [comment]
Hmm, weird, I didn't see that in my testing.

**Comment by metacosm** [comment]
Then again looking at the code again, it's indeed wrong. 🤦🏼

**Comment by metacosm** [comment]
OK, I think that it should now work properly. Can you give it another try, please?

**Comment by foal** [comment]
Yes, now I can build and deploy the app to the k8s. 

Thank you very much!
