### ISSUE TITLE
Shutdown race condition

### ISSUE THREAD

**Issue by scrocquesel** [quarkiverse/quarkus-operator-sdk#225]
Observe an exception with Mysql Schema operator

```
2022-02-07 22:53:37,587 INFO  [io.qua.ope.sam.mys.MySQLSchemaReconciler] (EventHandler-mysqlschemareconciler) Reconciling MySQLSchema with name: mydb1
2022-02-07 22:53:37,591 INFO  [io.qua.ope.sam.mys.sch.SchemaService] (EventHandler-mysqlschemareconciler) Connecting to 'jdbc:mysql://localhost:54376/default' with user 'root'
2022-02-07 22:53:37,654 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49698) MockWebServer[52141] received request: GET /apis/mysql.sample.javaoperatorsdk/v1/namespaces/test/mysqlschemas/mydb1 HTTP/1.1 and responded: HTTP/1.1 200 OK
2022-02-07 22:53:37,763 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49698) MockWebServer[52141] received request: GET /apis/mysql.sample.javaoperatorsdk/v1/namespaces/test/mysqlschemas/mydb1 HTTP/1.1 and responded: HTTP/1.1 200 OK
2022-02-07 22:53:37,784 INFO  [io.qua.ope.sam.mys.sch.SchemaService] (EventHandler-mysqlschemareconciler) Connecting to 'jdbc:mysql://localhost:54376/default' with user 'root'
2022-02-07 22:53:37,857 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49702) MockWebServer[52141] received request: GET /api/v1/namespaces/test/secrets/mydb1-secret HTTP/1.1 and responded: HTTP/1.1 404 Client Error
2022-02-07 22:53:37,865 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49698) MockWebServer[52141] received request: GET /apis/mysql.sample.javaoperatorsdk/v1/namespaces/test/mysqlschemas/mydb1 HTTP/1.1 and responded: HTTP/1.1 200 OK
2022-02-07 22:53:37,872 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49702) MockWebServer[52141] received request: POST /api/v1/namespaces/test/secrets HTTP/1.1 and responded: HTTP/1.1 200 OK
2022-02-07 22:53:37,873 INFO  [io.qua.ope.sam.mys.MySQLSchemaReconciler] (EventHandler-mysqlschemareconciler) Schema mydb1 created - updating CR status
2022-02-07 22:53:37,879 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49702) MockWebServer[52141] received request: PUT /apis/mysql.sample.javaoperatorsdk/v1/namespaces/test/mysqlschemas/mydb1/status HTTP/1.1 and responded: HTTP/1.1 200 OK
2022-02-07 22:53:37,968 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49698) MockWebServer[52141] received request: GET /apis/mysql.sample.javaoperatorsdk/v1/namespaces/test/mysqlschemas/mydb1 HTTP/1.1 and responded: HTTP/1.1 200 OK
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 42.129 s - in io.quarkiverse.operatorsdk.samples.mysqlschema.MySQLSchemaOperatorE2ETest
2022-02-07 22:53:38,035 INFO  [io.qua.ope.run.AppEventListener] (main) Quarkus Java Operator SDK extension is shutting down
2022-02-07 22:53:38,044 INFO  [io.qua.ope.sam.mys.sch.SchemaService] (Timer-1) Connecting to 'jdbc:mysql://localhost:54376/default' with user 'root'
2022-02-07 22:53:38,047 INFO  [io.qua.it.ope.cli.run.OpenShiftClientProducer] (main) Closing OpenShift client
2022-02-07 22:53:38,049 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49690) MockWebServer[52141] received request: GET /apis/mysql.sample.javaoperatorsdk/v1/mysqlschemas?resourceVersion=&allowWatchBookmarks=true&watch=true HTTP/1.1 and responded: HTTP/1.1 101 Switching Protocols
2022-02-07 22:53:38,062 INFO  [io.jav.ope.Operator] (main) Operator SDK 2.1.1 is shutting down...
2022-02-07 22:53:38,065 INFO  [io.jav.ope.pro.eve.sou.con.ControllerResourceEventSource] (main) Stopping informer 'mysqlschemareconciler' Controller -> io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer@77a35b2f
2022-02-07 22:53:38,065 INFO  [io.qua.ope.sam.mys.MySQLSchemaReconciler] (EventHandler-mysqlschemareconciler) Reconciling MySQLSchema with name: mydb1
2022-02-07 22:53:38,065 INFO  [io.qua.ope.sam.mys.sch.SchemaService] (EventHandler-mysqlschemareconciler) Connecting to 'jdbc:mysql://localhost:54376/default' with user 'root'
2022-02-07 22:53:38,074 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:49716) MockWebServer[52141] received request: PUT /apis/mysql.sample.javaoperatorsdk/v1/namespaces/test/mysqlschemas/mydb1/status HTTP/1.1 and responded: HTTP/1.1 200 OK
2022-02-07 22:53:38,075 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (EventHandler-mysqlschemareconciler) Error during event processing ExecutionScope{ resource id: CustomResourceID{name='mydb1', namespace='test'}, version: 1} failed.: java.lang.IllegalStateException: java.sql.SQLException: This pool is closed and does not handle any more connections!
        at io.quarkiverse.operatorsdk.samples.mysqlschema.schema.SchemaService.getConnection(SchemaService.java:118)
        at io.quarkiverse.operatorsdk.samples.mysqlschema.schema.SchemaService_ClientProxy.getConnection(Unknown Source)
        at io.quarkiverse.operatorsdk.samples.mysqlschema.MySQLSchemaReconciler.reconcile(MySQLSchemaReconciler.java:59)
        at io.quarkiverse.operatorsdk.samples.mysqlschema.MySQLSchemaReconciler.reconcile(MySQLSchemaReconciler.java:32)
        at io.quarkiverse.operatorsdk.samples.mysqlschema.MySQLSchemaReconciler_ClientProxy.reconcile(Unknown Source)
        at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:101)
        at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:76)
        at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:34)
        at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:75)
        at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:151)
        at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:117)
        at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:82)
        at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:51)
        at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:385)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: This pool is closed and does not handle any more connections!
        at io.agroal.pool.ConnectionPool.beforeAcquire(ConnectionPool.java:202)
        at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:228)
        at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
        at io.quarkiverse.operatorsdk.samples.mysqlschema.schema.SchemaService.getConnection(SchemaService.java:116)
        ... 16 more
```

When Quarkus shutdowns, Agroal datasource is closed and disposed, but there is an ongoing event being executed and it raise an error and the resource status is updated.

**Comment by metacosm** [comment]
How do you reproduce this?

**Comment by scrocquesel** [comment]
Sorry for late reply, i'm still trying to work on this and trying to repro the issue. But race condition are not easy to do so.

So far, I think the race condition comes from the fact that both the Datasource producer and Operator producer use `@PreDestroy`
https://github.com/quarkusio/quarkus/blob/7442da1ea202ffe51103ad52b2fb522d99623ee1/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSources.java#L377-L384

https://github.com/quarkiverse/quarkus-operator-sdk/blob/d97abbc0b02250572cce75c882408459238c4790/core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java#L43-L48

So it may happen the datasource is closed first and the operator is not fully stopped. I'm not sure if the order of the call is deterministic. But if it is based on dependency graph, as datasource is injected deeper in the operator graph, it should be destroyed first when the graph is destroyed.

BTW, do you know why the operator is not stopped by the AppEventListener ?

**Comment by scrocquesel** [comment]
Singleton Beans are destroyed in non deterministic order due to usage of a HashSet to iterate over them. There is nothing easy to do to forcibly reproduce it.

https://github.com/quarkusio/quarkus/blob/621ce7311ca42818a947a0d7f8cd3bec5b6ea57e/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/AbstractSharedContext.java#L72-L87

```java
@Override
public synchronized void destroy() {
    Set<ContextInstanceHandle<?>> values = instances.getPresentValues();
    // Destroy the producers first
    for (Iterator<ContextInstanceHandle<?>> iterator = values.iterator(); iterator.hasNext();) {
        ContextInstanceHandle<?> instanceHandle = iterator.next();
        if (instanceHandle.getBean().getDeclaringBean() != null) {
            instanceHandle.destroy();
            iterator.remove();
        }
    }
    for (ContextInstanceHandle<?> instanceHandle : values) {
        instanceHandle.destroy();
    }
    instances.clear();
}
```

While debugging `MySQLSchemaOperatorE2ETest:test` with a breakpoint on `OperatorProducer:destroy`, if lucky, datasource will be destroyed first and you will see errors and a PUT /status because eventsource are still firing.

Apart from stopping the operator in the AppEventListener, I'm clueless as to how it can be stopped a bit earlier than other singletons.

**Comment by metacosm** [comment]
> BTW, do you know why the operator is not stopped by the AppEventListener ?

Based on the commit history, it looks like this decision was made so that the operator would be stopped even in the event of an exception. If an exception occurs, the `ShutdownEvent` listener is not triggered.

**Comment by scrocquesel** [comment]
> 

Would it be possible to keep both then ? Stop the operator in AppEventListener and then let `@PreDestroy` do it again if necessary. I'm more concerned about false error during normal shutdown than when there is an exception bubbling.

**Comment by scrocquesel** [comment]
Been fixed a while ago by https://github.com/quarkiverse/quarkus-operator-sdk/pull/276
