### ISSUE TITLE
incorrect pom.xml with scaffolded app

### ISSUE THREAD

**Issue by sebastienblanc** [quarkiverse/quarkus-operator-sdk#248]
Hi,
I'm using the : 
```
operator-sdk version: "v1.18.0", commit: "c9c61b6921b29d731e64cd3cc33d268215fb3b25", kubernetes version: "v1.21", go version: "go1.17.6", GOOS: "darwin", GOARCH: "amd64"

```

I create a new operator : 
`operator-sdk init --domain sebi.redhat.com --plugins quarkus`
and an API : 
`operator-sdk create api --plugins quarkus  --version v1 --kind MyObject`

And then I start Quarkus dev mode : `mvn quarkus:dev` 

I'm getting this exception :
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:138)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
```
If I do a `mvn clean package` I get : 

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.7.0.Final:build (default) on project lasttest: Execution default of goal io.quarkus:quarkus-maven-plugin:2.7.0.Final:build failed: An API incompatibility was encountered while executing io.quarkus:quarkus-maven-plugin:2.7.0.Final:build: java.lang.NoSuchMethodError: 'io.quarkus.bootstrap.model.PathsCollection io.quarkus.bootstrap.app.QuarkusBootstrap.getApplicationRoot()'
```

**Comment by metacosm** [comment]
This has been addressed by operator-framework/java-operator-plugins#74. A new release of the plugin and of the `operator-sdk` tool should happen soon. Thank you!
