### ISSUE TITLE
Option to turn off MySQL tests

### ISSUE THREAD

**Issue by jesperpedersen** [quarkiverse/quarkus-operator-sdk#268]
Having `-Dquarkus.datasource.devservices.enabled=false` doesn't help as it just gives

```
2022-03-11 09:29:40,284 INFO  [io.qua.ope.csv.dep.ManifestsProcessor] (build-9) Generating CSV for mysqlschemareconciler controller -> /home/jews/PostgreSQL/OpenShift/quarkus-operator-sdk/samples/mysql-schema/target/manifests/mysqlschemareconciler.csv.yml
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.418 s <<< FAILURE! - in io.quarkiverse.operatorsdk.samples.mysqlschema.MySQLSchemaOperatorE2ETest
[ERROR] io.quarkiverse.operatorsdk.samples.mysqlschema.MySQLSchemaOperatorE2ETest.test  Time elapsed: 0.013 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: io.quarkiverse.operatorsdk.samples.mysqlschema.schema.SchemaService#defaultDataSource
	- declared on CLASS bean [types=[io.quarkiverse.operatorsdk.samples.mysqlschema.schema.SchemaService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.operatorsdk.samples.mysqlschema.schema.SchemaService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1202)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:272)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:134)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:462)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

... and a million more.
```

`docker` isn't installed, and therefore no daemon running either.

**Comment by metacosm** [comment]
You can compile using `-Dno-samples` to bypass the samples during the build.

**Comment by jesperpedersen** [comment]
Yeah, but I want `joke` :)

**Comment by scrocquesel** [comment]
after having done `mvn -Dquickly` at root, you should be able to change directory to samples/jokes and `mvn compile/test` from there
