### ISSUE TITLE
Operator restart failed when using KubernetesDependentResource

### ISSUE THREAD

**Issue by cdmikechen** [quarkiverse/quarkus-operator-sdk#335]
When using KubernetesDependentResource, I've found that If I restart operator, operator will recreate my dependent resource (a service). And then the service will report an error and fail to start.
I've checked I write a match method and it seems that operator does not call this method.
```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-05-05 13:53:10,074 INFO  [io.qua.ope.run.OperatorProducer] (Quarkus Main Thread) Quarkus Java Operator SDK extension 4.0.0.Beta1 (commit: cb69e0b on branch: cb69e0b6783a3f21081ef3b7942b33146b9326cc) built on Fri Apr 15 04:23:41 CST 2022
2022-05-05 13:53:10,099 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Registered reconciler: 'mqtttokafkapipelinereconciler' for resource: 'class com.pesco.operator.source.mqtt2kafka.crd.MqttToKafkaPipeline' for namespace(s): [all namespaces]
2022-05-05 13:53:10,099 INFO  [io.qua.ope.run.AppEventListener] (Quarkus Main Thread) Starting operator.
2022-05-05 13:53:10,099 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Operator SDK 3.0.0.RC1 (commit: e4790d6) built on Thu Apr 07 23:53:12 CST 2022 starting...
2022-05-05 13:53:10,100 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Client version: 5.12.2
2022-05-05 13:53:10,100 INFO  [io.jav.ope.pro.Controller] (Quarkus Main Thread) Starting 'mqtttokafkapipelinereconciler' controller for reconciler: com.pesco.operator.source.mqtt2kafka.MqttToKafkaPipelineReconciler_ClientProxy, resource: com.pesco.operator.source.mqtt2kafka.crd.MqttToKafkaPipeline
2022-05-05 13:53:10,519 INFO  [io.jav.ope.pro.Controller] (Quarkus Main Thread) 'mqtttokafkapipelinereconciler' controller started, pending event sources initialization
2022-05-05 13:53:10,523 INFO  [com.pes.ope.sou.mqt.dep.Mqtt2KafkaServiceResource] (EventHandler-mqtttokafkapipelinereconciler) 创建/修改 service kafka/mqtt-kafka-source
2022-05-05 13:53:10,531 INFO  [io.jav.ope.pro.dep.AbstractDependentResource] (EventHandler-mqtttokafkapipelinereconciler) Creating 'stream-pipeline-mqtt-kafka-source' Service for primary ResourceID{name='mqtt-kafka-source', namespace='kafka'}
2022-05-05 13:53:10,571 ERROR [com.pes.ope.sou.mqt.MqttToKafkaPipelineReconciler] (EventHandler-mqtttokafkapipelinereconciler) 创建资源时候发生异常！One or more DependentResource(s) failed:
		- Error reconciling dependent 'com.pesco.operator.source.mqtt2kafka.dependent.Mqtt2KafkaServiceResource': Failure executing: POST at: https://api-int.syokd4.sypesco.com:6443/api/v1/namespaces/kafka/services. Message: services "stream-pipeline-mqtt-kafka-source" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=stream-pipeline-mqtt-kafka-source, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "stream-pipeline-mqtt-kafka-source" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}). at: io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682): io.javaoperatorsdk.operator.AggregatedOperatorException: One or more DependentResource(s) failed:
		- Error reconciling dependent 'com.pesco.operator.source.mqtt2kafka.dependent.Mqtt2KafkaServiceResource': Failure executing: POST at: https://api-int.syokd4.sypesco.com:6443/api/v1/namespaces/kafka/services. Message: services "stream-pipeline-mqtt-kafka-source" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=stream-pipeline-mqtt-kafka-source, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "stream-pipeline-mqtt-kafka-source" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}). at: io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:209)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:165)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:34)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:164)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:133)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:101)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:74)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:49)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:353)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-05 13:53:10,605 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (EventHandler-mqtttokafkapipelinereconciler) Error during event processing ExecutionScope{ resource id: ResourceID{name='mqtt-kafka-source', namespace='kafka'}, version: 470870893} failed.: io.javaoperatorsdk.operator.AggregatedOperatorException: One or more DependentResource(s) failed:
		- Error reconciling dependent 'com.pesco.operator.source.mqtt2kafka.dependent.Mqtt2KafkaServiceResource': Failure executing: POST at: https://api-int.syokd4.sypesco.com:6443/api/v1/namespaces/kafka/services. Message: services "stream-pipeline-mqtt-kafka-source" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=stream-pipeline-mqtt-kafka-source, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "stream-pipeline-mqtt-kafka-source" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}). at: io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:209)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:165)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:34)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:164)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:133)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:101)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:74)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:49)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:353)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-05 13:53:10,609 INFO  [io.quarkus] (Quarkus Main Thread) stream-pipeline-operator 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.8.2.Final) started in 3.709s. Listening on: http://localhost:8080
2022-05-05 13:53:10,609 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-05-05 13:53:10,609 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, config-yaml, kubernetes, kubernetes-client, openshift-client, operator-sdk, smallrye-context-propagation, smallrye-health, vertx]
2022-05-05 13:53:12,611 INFO  [com.pes.ope.sou.mqt.dep.Mqtt2KafkaServiceResource] (EventHandler-mqtttokafkapipelinereconciler) 创建/修改 service kafka/mqtt-kafka-source
2022-05-05 13:53:12,612 INFO  [io.jav.ope.pro.dep.AbstractDependentResource] (EventHandler-mqtttokafkapipelinereconciler) Creating 'stream-pipeline-mqtt-kafka-source' Service for primary ResourceID{name='mqtt-kafka-source', namespace='kafka'}
2022-05-05 13:53:12,630 ERROR [com.pes.ope.sou.mqt.MqttToKafkaPipelineReconciler] (EventHandler-mqtttokafkapipelinereconciler) 创建资源时候发生异常！One or more DependentResource(s) failed:
		- Error reconciling dependent 'com.pesco.operator.source.mqtt2kafka.dependent.Mqtt2KafkaServiceResource': Failure executing: POST at: https://api-int.syokd4.sypesco.com:6443/api/v1/namespaces/kafka/services. Message: services "stream-pipeline-mqtt-kafka-source" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=stream-pipeline-mqtt-kafka-source, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "stream-pipeline-mqtt-kafka-source" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}). at: io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682): io.javaoperatorsdk.operator.AggregatedOperatorException: One or more DependentResource(s) failed:
		- Error reconciling dependent 'com.pesco.operator.source.mqtt2kafka.dependent.Mqtt2KafkaServiceResource': Failure executing: POST at: https://api-int.syokd4.sypesco.com:6443/api/v1/namespaces/kafka/services. Message: services "stream-pipeline-mqtt-kafka-source" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=stream-pipeline-mqtt-kafka-source, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "stream-pipeline-mqtt-kafka-source" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}). at: io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:209)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:165)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:34)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:164)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:133)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:101)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:74)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:49)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:353)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-05 13:53:12,645 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (EventHandler-mqtttokafkapipelinereconciler) Error during event processing ExecutionScope{ resource id: ResourceID{name='mqtt-kafka-source', namespace='kafka'}, version: 470871896} failed.: io.javaoperatorsdk.operator.AggregatedOperatorException: One or more DependentResource(s) failed:
		- Error reconciling dependent 'com.pesco.operator.source.mqtt2kafka.dependent.Mqtt2KafkaServiceResource': Failure executing: POST at: https://api-int.syokd4.sypesco.com:6443/api/v1/namespaces/kafka/services. Message: services "stream-pipeline-mqtt-kafka-source" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=stream-pipeline-mqtt-kafka-source, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "stream-pipeline-mqtt-kafka-source" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}). at: io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:209)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:165)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:34)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:164)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:133)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:101)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:74)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:49)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:353)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by csviri** [comment]
Hi @cdmikechen is you code open source? So I could take a look on it.
When the resource created does it have owner reference to the custom resource?

**Comment by metacosm** [comment]
You might need to override the `match` method because it looks like the SDK doesn't think the existing service matches what your operator requires for some reason…

**Comment by cdmikechen** [comment]
@csviri @metacosm 
I've debugged operator and found my mistake. I rename my resource name so that I need to overwrite `toSecondaryResourceID` method.
Thanks for your helps~
