### ISSUE TITLE
Executable built with native image not finding secondary resource

### ISSUE THREAD

**Issue by derlin** [quarkiverse/quarkus-operator-sdk#425]
**Context**

I have a very specific use-case that I described here: https://github.com/java-operator-sdk/java-operator-sdk/issues/1437

I now have a working implementation where I have a single reconciler watching `Db` resources. A Db resource references a `Config` by name and namespace. This config contains information on how to connect to a database. Since root username and password are sensitive, they are stored in a `Secret` (let's call it *credentials secret*) that has exactly the same name and namespace as the `Config`.

The implementation can be found here: https://github.com/derlin/josdk-operator-dependent-crs

**Problem**

The same operator compiled with `-Pnative` doesn't throw any exception, but is not able to find the credentials secret anymore. The exact error is:
```
Caused by: javax.validation.ValidationException: Missing credentials secret
        at ch.derlin.configreconciler.DbReconciler.lambda$reconcile$1(DbReconciler.java:67)
        at java.util.Optional.orElseThrow(Optional.java:408)
        at ch.derlin.configreconciler.DbReconciler.reconcile(DbReconciler.java:66)
```
and happens on the line: 
```java
context.getSecondaryResource(Secret.class, CREDENTIALS_SECRET_INFORMER)
```

As I said, the operator running on JVM works with the exact same resources in kube. I couldn't find any clue on what is happening by comparing the logs, which look exactly the same in both context

**Reproduce**

To reproduce, clone the repo https://github.com/derlin/josdk-operator-dependent-crs (branch main). Connect to a k3d cluster and run:
```bash
mvn package # generate the CRDs
make install # install the CRDs

# create a credentials secret and a default config
kubectl apply -f samples/credentials-secret.yaml
kubectl apply -f samples/config.v1.yaml

# create a db (will trigger a reconciliation)
helm install dbs helm-test/dbs --set num=1
```

Now, run the operator normally. The reconciliation should succeed. Build the operator using graalvm (you need graalvm installed) and run it on the same kube context:
```bash
mvn -Pnative
./target/*-runner
```
You should see the error.

Any idea what is happening or how to debug this ?

**Comment by metacosm** [comment]
The issue doesn't exist anymore if you use 4.0.3 instead of 4.0.1. You can also use the new `quarkus.operator-sdk.crd.generate-all=true` property and remove the `crd-generator-apt` dependency.

Now, regarding the actual issue: the problem is most likely a class that didn't get properly registered for reflection. In that situation, it's very common to get a `null` object when Jackson tries to deserialise the object instead of an error. It's a little surprising that this would occur on a `Secret` which should have been registered for reflection but I know that there have been some fixes on that front in Quarkus in more recent versions, which would get pulled when using more recent versions of the extension.

Let me know how things go.

**Comment by derlin** [comment]
@metacosm Thank you for the reply. I applied the changes you proposed, but now I get a `ClassCastException`, still on the same line (`context.getSecondaryResource(Secret.class, <name>)`):
```
2022-10-13 08:02:54,177 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (ReconcilerExecutor-dbreconciler-69) Error during event processing ExecutionScope{ resource id: ResourceID{name='dbs-0', namespace='lala'}, version: 139972} failed.: io.javaoperatorsdk.operator.OperatorException: java.lang.ClassCastException: io.fabric8.kubernetes.api.model.GenericKubernetesResource cannot be cast to io.fabric8.kubernetes.api.model.Secret
        at io.javaoperatorsdk.operator.monitoring.micrometer.MicrometerMetrics.lambda$timeControllerExecution$0(MicrometerMetrics.java:58)
        at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:65)
        at io.javaoperatorsdk.operator.monitoring.micrometer.MicrometerMetrics.timeControllerExecution(MicrometerMetrics.java:54)
        at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:87)
        at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:135)
        at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:115)
        at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:86)
        at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:59)
        at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:395)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.lang.ClassCastException: io.fabric8.kubernetes.api.model.GenericKubernetesResource cannot be cast to io.fabric8.kubernetes.api.model.Secret
        at ch.derlin.configreconciler.DbReconciler.reconcile(DbReconciler.java:66)
        at ch.derlin.configreconciler.DbReconciler.reconcile(DbReconciler.java:34)
        at ch.derlin.configreconciler.DbReconciler_ClientProxy.reconcile(Unknown Source)
        at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:130)
        at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:88)
        at io.javaoperatorsdk.operator.monitoring.micrometer.MicrometerMetrics.lambda$timeControllerExecution$0(MicrometerMetrics.java:56)
        ... 13 more
```
Where you able to run the native executable on your side without error ?

**Comment by metacosm** [comment]
I did manage to get it to run once yesterday but it failed with the same error just now as I tried again. The exception you get is due to the fact that, for some reason, the fabric8 client fails to deserialize the `Secret` so it falls back to a `GenericKubernetesResource`, so there's still some deserialization problem… 🤔

**Comment by derlin** [comment]
And you were able to get the same result ? Any idea what is causing this or how to fix it ?

**Comment by metacosm** [comment]
Still looking into it… I think that _somehow_ the Kubernetes client extension for Quarkus loses the registration for reflection but I am unsure if that's really the cause or why that is at the moment…

**Comment by derlin** [comment]
still couldn't pinpoint the issue ?

**Comment by metacosm** [comment]
Got sidetracked on other issues, will get back to it next week, hopefully. Sorry about that!

**Comment by metacosm** [comment]
Hi @derlin, could you give #435 a try? I think this should address this issue. Let me know how it goes!

**Comment by derlin** [comment]
@metacosm It solved the problem, thanks ! (I am now struggling with other native issues, but unrelated with the SDK this time). Thank you very much for your help and fast response !

**Comment by metacosm** [comment]
LOL, I wouldn't have described my response as "fast" but if you're happy with it, I'm happy as well! 😁
