### ISSUE TITLE
bug: dev mode hangs forever when shutting down an operator that uses the leader election

### ISSUE THREAD

**Issue by nicoloboschi** [quarkiverse/quarkus-operator-sdk#450]
```
2022-11-29 18:07:51,578 INFO  [io.jav.ope.Operator] (Shutdown thread) Operator SDK 4.1.3-SNAPSHOT is shutting down...
2022-11-29 18:07:51,642 ERROR [io.fab.kub.cli.ext.lea.LeaderElector] (Shutdown thread) Exception occurred while releasing lock 'LeaseLock: ns - pulsar-operator-lease (90a7a506-8e88-46dd-bf52-6f9d94676d73)' [Error Occurred After Shutdown]: io.fabric8.kubernetes.client.extended.leaderelection.resourcelock.LockException: Unable to update LeaseLock
        at io.fabric8.kubernetes.client.extended.leaderelection.resourcelock.LeaseLock.update(LeaseLock.java:102)
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.release(LeaderElector.java:139)
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.stopLeading(LeaderElector.java:120)
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$null$1(LeaderElector.java:94)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2512)
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$null$0(LeaderElector.java:92)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2512)
        at io.javaoperatorsdk.operator.LeaderElectionManager.stop(LeaderElectionManager.java:98)
        at io.javaoperatorsdk.operator.Operator.stop(Operator.java:121)
        at io.quarkiverse.operatorsdk.runtime.AppEventListener.onShutdown(AppEventListener.java:39)
        at io.quarkiverse.operatorsdk.runtime.AppEventListener_Observer_onShutdown_dd47986a36bed17ca36ae7289cdaf215631ad28e.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder$2.run(ArcRecorder.java:105)
        at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)
        at io.quarkus.runtime.StartupContext.close(StartupContext.java:73)
        at io.quarkus.runner.ApplicationImpl.doStop(Unknown Source)
        at io.quarkus.runtime.Application.stop(Application.java:208)
        at io.quarkus.runtime.Application.stop(Application.java:155)
        at io.quarkus.runtime.ApplicationLifecycleManager$ShutdownHookThread.run(ApplicationLifecycleManager.java:431)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://localhost:61876/apis/coordination.k8s.io/v1/namespaces/ns/leases/pulsar-operator-lease. Message: Operation cannot be fulfilled on leases.coordination.k8s.io "pulsar-operator-lease": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=coordination.k8s.io, kind=leases, name=pulsar-operator-lease, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on leases.coordination.k8s.io "pulsar-operator-lease": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:517)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:551)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleUpdate(OperationSupport.java:347)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleUpdate(BaseOperation.java:680)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$replace$0(HasMetadataOperation.java:167)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:172)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:113)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:41)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.replace(BaseOperation.java:1043)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.replace(BaseOperation.java:88)
        at io.fabric8.kubernetes.client.extended.leaderelection.resourcelock.LeaseLock.update(LeaseLock.java:100)
        ... 27 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://localhost:61876/apis/coordination.k8s.io/v1/namespaces/ns/leases/pulsar-operator-lease. Message: Operation cannot be fulfilled on leases.coordination.k8s.io "pulsar-operator-lease": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=coordination.k8s.io, kind=leases, name=pulsar-operator-lease, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on leases.coordination.k8s.io "pulsar-operator-lease": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:709)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:689)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:640)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:576)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$retryWithExponentialBackoff$2(OperationSupport.java:618)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$4.onResponse(OkHttpClientImpl.java:277)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)



--
Tests paused
Press [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>
2022-11-29 18:07:51,681 INFO  [io.jav.ope.LeaderElectionManager] (Shutdown thread) Stopped leading for identity: 90a7a506-8e88-46dd-bf52-6f9d94676d73. Exiting.

```

I do have an operator that uses the leader election. When quitting from the dev mode (`mvn quarkus:dev`) the process remains stuck. I did a thread dump and the quarkus mojo thread is sleeping. 

```
"main" #1 [9987] prio=5 os_prio=31 cpu=4662.15ms elapsed=154.26s tid=0x00007f9fd4009000 nid=9987 waiting on condition  [0x000070000f39e000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep0(java.base@19.0.1/Native Method)
        at java.lang.Thread.sleep(java.base@19.0.1/Thread.java:465)
        at io.quarkus.maven.DevMojo.execute(DevMojo.java:426)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
```

My guess is the System.exit(1) in the sdk causes this situation: 
https://github.com/java-operator-sdk/java-operator-sdk/blob/fb9dc1aeef2a5b0c9faf69286d39f16409f332f7/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/LeaderElectionManager.java#L74-L80

related issue: https://github.com/java-operator-sdk/java-operator-sdk/issues/1585

I'm using 5.0.2.Beta

**Comment by nicoloboschi** [comment]
No I don't think so. This issue seems related to the way the quarkus mojo execution handles the system exit 

btw I've a VERY DIRTY workaround. Setting this in a controller shutdown hook

```
if (LaunchMode.current().isDevOrTest()) {
            ConfigurationServiceProvider.reset();
            client.leases().withName(LeaderElectionConfig.PULSAR_OPERATOR_LEASE_NAME).delete();
}
```

**Comment by metacosm** [comment]
Leader election probably shouldn't be started at all in dev mode, actually…

**Comment by nicoloboschi** [comment]
> Leader election probably shouldn't be started at all in dev mode, actually…

Yes that was my first attempt to workaround it but unfortunately there's no way to conditionally enable the leader election
