### ISSUE TITLE
java.lang.IllegalArgumentException: There are multiple EventSources registered for type when upgrading from 5.0.0.Beta2 to 5.0.0

### ISSUE THREAD

**Issue by juangon** [quarkiverse/quarkus-operator-sdk#465]
In the same project that worked fine in 5.0.0.Beta2, now I have the error:
```
java.lang.IllegalArgumentException: There are multiple EventSources registered for type io.strimzi.api.kafka.model.KafkaTopic
```
I have multiple dependent KafkaTopics and I use a ResourceDiscriminator. I am not using `useEventSourceWithName` as I want to avoid implementing `prepareEventSources` method in reconciler, as the java-operator-sdk example does. This approach worked fine in 5.0.0.Beta2 but it doesn't work now.

Any ideas? Thanks!

**Comment by metacosm** [comment]
Hi @juangon,

Can you provide a more complete stack trace, please? Thanks in advance.

**Comment by juangon** [comment]
Here you have @metacosm . Thanks!

```
2022-12-29 23:13:54,248 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (ReconcilerExecutor-teis-app-controller-240) Error during event processing ExecutionScope{ resource id: ResourceID{name='teis-app-proactivanet', namespace='teis-proactivanet-soriana-demo'}, version: 795330345} failed.: io.javaoperatorsdk.operator.AggregatedOperatorException: Exception(s) during workflow execution. Details:
com.teis.operator.teisbackend.TeisBackendDependent -> java.lang.NullPointerException
	at io.javaoperatorsdk.operator.processing.dependent.workflow.WorkflowResult.throwAggregateExceptionIfErrorsPresent(WorkflowResult.java:40)
	at io.javaoperatorsdk.operator.processing.dependent.workflow.WorkflowReconcileResult.throwAggregateExceptionIfErrorsPresent(WorkflowReconcileResult.java:9)
	at io.javaoperatorsdk.operator.processing.dependent.workflow.DefaultWorkflow.reconcile(DefaultWorkflow.java:92)
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:140)
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:103)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:206)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:102)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:141)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:121)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:91)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:64)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-12-29 23:13:54,333 WARN  [io.fab.kub.cli.dsl.int.VersionUsageUtils] (InformerWrapper [kafkas.kafka.strimzi.io/v1beta2] 255) The client is using resource type 'kafkas' with unstable version 'v1beta2'
2022-12-29 23:13:54,592 INFO  [io.jav.ope.pro.Controller] (ForkJoinPool.commonPool-worker-3) 'teis-backend-controller' controller started, pending event sources initialization
2022-12-29 23:13:54,598 INFO  [io.jav.ope.pro.dep.AbstractDependentResource] (pool-8-thread-3) Updating 'teis-backend-secrets' Secret for primary ResourceID{name='teis-backend-teis-proactivanet-soriana-demo', namespace='teis-proactivanet-soriana-demo'}
2022-12-29 23:13:54,618 INFO  [io.jav.ope.pro.Controller] (ForkJoinPool.commonPool-worker-13) 'teis-kafka-controller' controller started, pending event sources initialization
2022-12-29 23:13:54,617 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (ReconcilerExecutor-teis-backend-controller-270) Error during event processing ExecutionScope{ resource id: ResourceID{name='teis-backend-teis-proactivanet-soriana-demo', namespace='teis-proactivanet-soriana-demo'}, version: 795330341} failed.: io.javaoperatorsdk.operator.AggregatedOperatorException: Exception(s) during workflow execution. Details:
com.teis.operator.teisbackend.kafka.KafkaBackendTicketPredictedDependent -> java.lang.IllegalArgumentException: There are multiple EventSources registered for type io.strimzi.api.kafka.model.KafkaTopic, you need to provide a name to specify which EventSource you want to query. Known names: kafka-backend-topic-ticket-predicted,kafka-backend-topic-ticket-import-errors,kafka-backend-topic-ticket-added
 - com.teis.operator.teisbackend.kafka.KafkaBackendTicketImportErrorsDependent -> java.lang.IllegalArgumentException: There are multiple EventSources registered for type io.strimzi.api.kafka.model.KafkaTopic, you need to provide a name to specify which EventSource you want to query. Known names: kafka-backend-topic-ticket-predicted,kafka-backend-topic-ticket-import-errors,kafka-backend-topic-ticket-added
 - com.teis.operator.teisbackend.kafka.KafkaBackendTicketAddedDependent -> java.lang.IllegalArgumentException: There are multiple EventSources registered for type io.strimzi.api.kafka.model.KafkaTopic, you need to provide a name to specify which EventSource you want to query. Known names: kafka-backend-topic-ticket-predicted,kafka-backend-topic-ticket-import-errors,kafka-backend-topic-ticket-added
	at io.javaoperatorsdk.operator.processing.dependent.workflow.WorkflowResult.throwAggregateExceptionIfErrorsPresent(WorkflowResult.java:40)
	at io.javaoperatorsdk.operator.processing.dependent.workflow.WorkflowReconcileResult.throwAggregateExceptionIfErrorsPresent(WorkflowReconcileResult.java:9)
	at io.javaoperatorsdk.operator.processing.dependent.workflow.DefaultWorkflow.reconcile(DefaultWorkflow.java:92)
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:140)
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:103)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:206)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:102)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:141)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:121)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:91)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:64)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by juangon** [comment]
> Hi @juangon,
> 
> Can you provide a more complete stack trace, please? Thanks in advance. Could you also explain the reasoning behind not using `useEventSourceWithName`? I tend to think that `ResourceDiscriminator` should be removed but it seems your use case is proving me wrong so would like to hear more about it… smile

It's fine for me to use `useEventSourceWithName` but as long as I don't have to reimplement `prepareEventSources` because in reconcilers I have more than one type of `DependentResource` and wouldn't like to prepare all of those event sources, as I have all annotations in place.

**Comment by metacosm** [comment]
You shouldn't have to re-implement `prepareEventSources`, I think simply providing an explicit name for your dependents should be enough to fix the issue. You probably don't need to use `useEventSourceWithName` either. Would you mind sharing your controller's configuration along with the dependents definition (the class signature ought to be enough)?

**Comment by juangon** [comment]
Yes, I have a name for those dependents (@DependentResource name), in fact those james are showing un logs I've sent. Any other idea? Thanks very much!

**Comment by juangon** [comment]
Here you have the reconciler config @metacosm :

```
@ControllerConfiguration(name = TeisBackendReconciler.TEIS_BACKEND_CONTROLLER,
 dependents = { 
        @Dependent(type = KafkaBackendTicketImportErrorsDependent.class, name = "kafka-backend-topic-ticket-import-errors", readyPostcondition =  KafkaBackendTicketImportErrorsDependent.class),
        @Dependent(type = KafkaBackendTicketAddedDependent.class, name = "kafka-backend-topic-ticket-added", readyPostcondition =  KafkaBackendTicketAddedDependent.class),
        @Dependent(type = KafkaBackendTicketPredictedDependent.class, name = "kafka-backend-topic-ticket-predicted", readyPostcondition =  KafkaBackendTicketPredictedDependent.class),
        @Dependent(type = TeisBackendMariaDBDependent.class, name = "teis-backend-mariadb", readyPostcondition = TeisBackendMariaDBDependent.class),
        @Dependent(type = TeisBackendConfigMapDependent.class, name="teis-backend-config"),
        @Dependent(type = TeisBackendSecretDependent.class, name="teis-backend-secret"),
        @Dependent(type = TeisBackendDeploymentDependent.class, 
            dependsOn = { 
                "kafka-backend-topic-ticket-import-errors",
                "kafka-backend-topic-ticket-added",  
                "kafka-backend-topic-ticket-predicted",             
                "teis-backend-mariadb",
                "teis-backend-config",
                "teis-backend-secret"}),
        @Dependent(type = TeisBackendServiceDependent.class)
    })
```

**Comment by metacosm** [comment]
I'm investigating the root cause, there seems to be funny going on. In the mean time, could you try the following configuration and let me know how it goes, please:

 ```
 @ControllerConfiguration(name = TeisBackendReconciler.TEIS_BACKEND_CONTROLLER,
  dependents = { 
         @Dependent(type = KafkaBackendTicketImportErrorsDependent.class, name = "kafka-backend-topic-ticket-import-errors", readyPostcondition =  KafkaBackendTicketImportErrorsDependent.class, useEventSourceWithName="kafka-backend-topic-ticket-predicted"),
         @Dependent(type = KafkaBackendTicketAddedDependent.class, name = "kafka-backend-topic-ticket-added", readyPostcondition =  KafkaBackendTicketAddedDependent.class, useEventSourceWithName="kafka-backend-topic-ticket-predicted"),
         @Dependent(type = KafkaBackendTicketPredictedDependent.class, name = "kafka-backend-topic-ticket-predicted", readyPostcondition =  KafkaBackendTicketPredictedDependent.class),
         @Dependent(type = TeisBackendMariaDBDependent.class, name = "teis-backend-mariadb", readyPostcondition = TeisBackendMariaDBDependent.class),
         @Dependent(type = TeisBackendConfigMapDependent.class, name="teis-backend-config"),
         @Dependent(type = TeisBackendSecretDependent.class, name="teis-backend-secret"),
         @Dependent(type = TeisBackendDeploymentDependent.class, 
             dependsOn = { 
                 "kafka-backend-topic-ticket-import-errors",
                 "kafka-backend-topic-ticket-added",  
                 "kafka-backend-topic-ticket-predicted",             
                 "teis-backend-mariadb",
                 "teis-backend-config",
                 "teis-backend-secret"}),
         @Dependent(type = TeisBackendServiceDependent.class)
     })
 ```

**Comment by juangon** [comment]
Ok so with your snippet @metacosm  it seems that one of two Exceptions went away. The NullPointer is still there though:

```2023-01-02 18:00:49,355 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (ReconcilerExecutor-teis-app-controller-287) Error during event processing ExecutionScope{ resource id: ResourceID{name='teis-app-proactivanet', namespace='teis-proactivanet-soriana-demo'}, version: 803492499} failed.: io.javaoperatorsdk.operator.AggregatedOperatorException: Exception(s) during workflow execution. Details:
com.teis.operator.teisbackend.TeisBackendDependent -> java.lang.NullPointerException
	at io.javaoperatorsdk.operator.processing.dependent.workflow.WorkflowResult.throwAggregateExceptionIfErrorsPresent(WorkflowResult.java:40)
	at io.javaoperatorsdk.operator.processing.dependent.workflow.WorkflowReconcileResult.throwAggregateExceptionIfErrorsPresent(WorkflowReconcileResult.java:9)
	at io.javaoperatorsdk.operator.processing.dependent.workflow.DefaultWorkflow.reconcile(DefaultWorkflow.java:92)
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:140)
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:103)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:206)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:102)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:141)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:121)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:91)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:64)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Any idea about that? Thanks very much!

**Comment by juangon** [comment]
Just sent to your email @metacosm . Thanks very much for your help!
