### ISSUE TITLE
NullPointerException in OperatorProducer.java:27

### ISSUE THREAD

**Issue by scrocquesel** [quarkiverse/quarkus-operator-sdk#47]
Hello,

When running, I got this startup error. The configuration is done the same way I do for other operators. If you have any insight to where to look at.
I'm using 1.8.4 with quarkus 1.13.4.

```
2021-05-20 18:07:56,553 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.NullPointerException
        at io.quarkiverse.operatorsdk.runtime.OperatorProducer.operator(OperatorProducer.java:27)
        at io.quarkiverse.operatorsdk.runtime.OperatorProducer_Subclass.operator$$superaccessor1(OperatorProducer_Subclass.zig:235)
        at io.quarkiverse.operatorsdk.runtime.OperatorProducer_Subclass$$function$$1.apply(OperatorProducer_Subclass$$function$$1.zig:53)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkiverse.operatorsdk.runtime.OperatorProducer_Subclass.operator(OperatorProducer_Subclass.zig:186)
        at io.quarkiverse.operatorsdk.runtime.OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.create(OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.zig:367)
        at io.quarkiverse.operatorsdk.runtime.OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.create(OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.zig:382)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkiverse.operatorsdk.runtime.OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.get(OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.zig:414)
        at io.quarkiverse.operatorsdk.runtime.OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.get(OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.zig:430)
        at oda.operators.QuarkusOperator_Bean.create(QuarkusOperator_Bean.zig:271)
        at oda.operators.QuarkusOperator_Bean.create(QuarkusOperator_Bean.zig:311)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
        at oda.operators.QuarkusOperator_ClientProxy.arc$delegate(QuarkusOperator_ClientProxy.zig:67)
        at oda.operators.QuarkusOperator_ClientProxy.run(QuarkusOperator_ClientProxy.zig:126)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:122)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at oda.operators.QuarkusOperator.main(QuarkusOperator.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Also, note sure if it can be related but when terminating a log say 

```
2021-05-20 18:23:45,592 INFO  [io.qua.it.ope.cli.run.OpenShiftClientProducer] (Quarkus Main Thread) Closing OpenShift client
```

while i'm on a vanilla kubernetes

**Comment by metacosm** [comment]
This seems to indicate that the SDK cannot find the configuration for your controller.  What is the name of your controller and/or its associated class name?

**Comment by scrocquesel** [comment]
I upgraged from 1.7.5 (old repo version).
I use the same configuration 

```properties
quarkus.operator-sdk.controllers.RabbitmqUser.namespaces=default
```

```java
@Controller(name = RabbitmqUserController.NAME)
@ApplicationScoped
public class RabbitmqUserController implements ResourceController<RabbitmqUser> {

    protected static final String NAME = "RabbitmqUser";
```

**Comment by metacosm** [comment]
I am unable to reproduce the issue here. Do you have any code that would exhibit the issue that I could look at?

**Comment by metacosm** [comment]
I've created a PR to check this issue: https://github.com/quarkiverse/quarkus-operator-sdk/pull/54.

**Comment by scrocquesel** [comment]
I give it another try today and it appears that's it is related to the `@ApplicationScoped` annotation. I suspect a proxy is created in between and the name of the controller is a bit modified

**Comment by scrocquesel** [comment]
> I give it another try today and it appears that's it is related to the `@ApplicationScoped` annotation. I suspect a proxy is created in between and the name of the controller is a bit modified

I'm setting the name in the controller annotation so this shouldn't be the issue anyway, right ?

**Comment by metacosm** [comment]
Do you have a project that I could look at?
I was suspecting the presence of the `@ApplicationScoped` annotation to maybe impact things but the test I added in #54 uses that annotation without issue.

**Comment by metacosm** [comment]
> > I give it another try today and it appears that's it is related to the `@ApplicationScoped` annotation. I suspect a proxy is created in between and the name of the controller is a bit modified
> 
> I'm setting the name in the controller annotation so this shouldn't be the issue anyway, right ?

Well it depends if we can still match the name to the controller class despite the presence of proxies. The extension already has some heuritics to deal with proxies but maybe these need to be extended.

**Comment by scrocquesel** [comment]
@metacosm see above the repro project.

**Comment by metacosm** [comment]
Thanks for taking the time to create a reproducer. Still not sure why I can't replicate the issue during the tests but I've identified and solved the problem…
