### ISSUE TITLE
Quarkus 2 upgrade

### ISSUE THREAD

**Issue by mswiderski** [quarkiverse/quarkus-operator-sdk#50]
While trying out the operator on top quarkus  (2.0.0.CR1) it fails at build time with following exception

````
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.0.0.CR1:build (default) on project mysql-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.NoSuchFieldError: INDENT_ARRAYS_WITH_INDICATOR
[ERROR] 	at io.dekorate.utils.Serialization.<clinit>(Serialization.java:59)
[ERROR] 	at io.dekorate.processor.SimpleFileWriter.write(SimpleFileWriter.java:133)
[ERROR] 	at io.dekorate.SessionWriter.lambda$write$1(SessionWriter.java:57)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[ERROR] 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[ERROR] 	at io.dekorate.SessionWriter.write(SessionWriter.java:56)
[ERROR] 	at io.dekorate.Session.close(Session.java:253)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$4(KubernetesProcessor.java:162)
[ERROR] 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:120)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
````

So it might be expected due to version incompatibilies but wanted to report and ask what is the plan to release version that can be based on quarkus 2.

**Comment by metacosm** [comment]
We haven't looked at Quarkus 2 yet but we will starting next week now that CR1 is out.

**Comment by metacosm** [comment]
2.0.0.Beta1 has been released which uses Quarkus 2.0.0.CR2 if you want to give it a spin.

**Comment by mswiderski** [comment]
excellent @metacosm, will give it a try later today and post back results, thanks a lot!

**Comment by mswiderski** [comment]
with 2.0.0.Beta1 it works as expected, thanks a lot!

**Comment by metacosm** [comment]
Thanks for checking!
