### ISSUE TITLE
During Development, QuarkusConfigurationService Is Not Available.

### ISSUE THREAD

**Issue by hmadison** [quarkiverse/quarkus-operator-sdk#588]
When using `./gradlew quarkusDev` to start the operator, the following error appears.  It consistently happens at startup.

```sh
2023-05-16 08:37:33,187 WARN  [io.qua.ope.run.dev.ControllersSupplier] (Quarkus Main Thread) Couldn't retrieve controllers information because QuarkusConfigurationService is not available: java.lang.NullPointerException: Cannot invoke "io.javaoperatorsdk.operator.Operator.getRegisteredControllers()" because the return value of "io.quarkus.arc.InstanceHandle.get()" is null
        at io.quarkiverse.operatorsdk.runtime.devconsole.ControllersSupplier.get(ControllersSupplier.java:26)
        at io.quarkiverse.operatorsdk.runtime.devconsole.ControllersSupplier.get(ControllersSupplier.java:17)
        at io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder.addInfo(DevConsoleRecorder.java:33)
        at io.quarkus.deployment.steps.DevConsoleProcessor$runtimeTemplates308161071.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.DevConsoleProcessor$runtimeTemplates308161071.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.InjectableBean.getScope()" because "this.bean" is null
                at io.quarkus.arc.impl.AbstractInstanceHandle.destroy(AbstractInstanceHandle.java:64)
                at io.quarkus.arc.InstanceHandle.close(InstanceHandle.java:69)
                at io.quarkiverse.operatorsdk.runtime.devconsole.ControllersSupplier.get(ControllersSupplier.java:24)
                ... 17 more
```

Gradle Version: `8.1.1`
Quarkus Version: `3.0.3.Final`
operator-sdk version: `6.0.2`

**Comment by hmadison** [comment]
This error appeasers to go away if I remove any reference to `quarkus-universe-bom`.

**Comment by metacosm** [comment]
Do you have any details on when this happens? I had seen this problem a few times at some point but I haven't seen it in a while in my testing.

**Comment by metacosm** [comment]
> This error appears to go away if I remove any reference to `quarkus-universe-bom`.

That's weird. By the way, you shouldn't need to use the `quarkus-universe-bom` in your operator. Any particular reason why you include this dependency?

**Comment by hmadison** [comment]
> Any particular reason why you include this dependency?

Its looking like its getting brought in via a transitive dependency. It looks like something I can sort out on my end.

**Comment by metacosm** [comment]
> > Any particular reason why you include this dependency?
> 
> Its looking like its getting brought in via a transitive dependency. It looks like something I can sort out on my end.

OK, let me know how it goes.

**Comment by hmadison** [comment]
I've found the affected internal dependency. Sorry for the confusion!
