### ISSUE TITLE
CustomResource Java class not found in native packaging 

### ISSUE THREAD

**Issue by lbroudoux** [quarkiverse/quarkus-operator-sdk#59]
Hi!

I'm working on the operator for [Apicurio Studio](https://www.apicur.io/studio/) (see https://github.com/lbroudoux/apicurio-studio-operator) and I'm facing an issue when compiled / packaged in native mode.

I've developed and tested locally and everything is working fine:
* API object are in an `api` maven module,
* Operator lives into its own `operator` module.

Native compilation and packaging executes well and I can see in `/target/[...]native-image-source-jar` that `api` module is correctly pulled and included. However on pod startup in OpenShift, I encounter the following exception:

```sh
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-06-03 13:50:50,594 INFO  [io.quarkus] (main) apicurio-studio-kube-operator 0.0.1-SNAPSHOT native (powered by Quarkus 1.13.3.Final) started in 0.011s. Listening on: http://0.0.0.0:8080
2021-06-03 13:50:50,594 INFO  [io.quarkus] (main) Profile prod activated.
2021-06-03 13:50:50,594 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, kubernetes-client, openshift-client, operator-sdk, smallrye-health]
2021-06-03 13:50:50,596 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: Couldn't find class io.apicurio.studio.operator.api.ApicurioStudio
	at io.quarkiverse.operatorsdk.runtime.QuarkusControllerConfiguration.loadClass(QuarkusControllerConfiguration.java:78)
	at io.quarkiverse.operatorsdk.runtime.QuarkusControllerConfiguration.getCustomResourceClass(QuarkusControllerConfiguration.java:69)
	at io.javaoperatorsdk.operator.Operator.register(Operator.java:137)
	at io.javaoperatorsdk.operator.Operator.register(Operator.java:97)
	at io.quarkiverse.operatorsdk.runtime.OperatorProducer.operator(OperatorProducer.java:28)
	at io.quarkiverse.operatorsdk.runtime.OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.create(OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.zig:379)
	at io.quarkiverse.operatorsdk.runtime.OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.create(OperatorProducer_ProducerMethod_operator_847eb6ef05d4600d92e563d1fb80474eed9238e0_Bean.zig:394)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
```

Would you have any hints or checks to troubleshoot that?

**Comment by metacosm** [comment]
Unfortunately, I don't have much in ways of generic troubleshooting tips apart from what's in https://quarkus.io/guides/building-native-image#debugging-native-executable and https://quarkus.io/guides/writing-native-applications-tips

The good new, though, is that I've fixed the issue in the extension. It was a known issue with the fabric8 client extension: https://github.com/quarkusio/quarkus/pull/17472

**Comment by metacosm** [comment]
Note also that you shouldn't need to add these lines https://github.com/lbroudoux/apicurio-studio-operator/blob/main/operator/src/main/resources/application.properties#L8-L9 to your `application.properties`: this is automatically done by the extension: https://github.com/quarkiverse/quarkus-operator-sdk/blob/main/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java#L86-L87

**Comment by lbroudoux** [comment]
Thanks for update. 

I've tried upgrading to new `1.9.2` with upgrade to Quarkus `1.3.6.Final`. My initial issue after native compilation disappeared and deployment. Cool!

However, I'm facing 2 new issues:

1) Seems that the Java Operator SDK or Kubernetes Client needs a mandatory `ClusterRoleBinding` to be able to read `customresourcedefinitions.apiextensions.k8s.io` at the cluster scope. This is a bit odd as my operator is namespaced-scope only. Having to add a cluster-level role and associate binding is not always appreciated by Ops...

2) Still in Java Operator SDK - whether with fixed permissions or `cluster-admin` role - there's a NPE thrown when customresource is updated. 

```
2021-06-09 11:46:38,764 ERROR [io.fab.kub.cli.dsl.int.WatcherWebSocketListener] (OkHttp https://api.cluster-0f5f.0f5f.sandbox1056.opentlc.com:6443/...) Unhandled exception encountered in watcher event handler: java.lang.NullPointerException
        at io.javaoperatorsdk.operator.processing.CustomResourceCache.clone(CustomResourceCache.java:67)
        at java.base/java.util.Optional.map(Optional.java:265)
        at io.javaoperatorsdk.operator.processing.CustomResourceCache.getLatestResource(CustomResourceCache.java:61)
        at io.javaoperatorsdk.operator.processing.event.DefaultEventSourceManager.getLatestResource(DefaultEventSourceManager.java:152)
        at io.javaoperatorsdk.operator.processing.DefaultEventHandler.executeBufferedEvents(DefaultEventHandler.java:120)
        at io.javaoperatorsdk.operator.processing.DefaultEventHandler.handleEvent(DefaultEventHandler.java:110)
        at io.javaoperatorsdk.operator.processing.event.internal.CustomResourceEventSource.eventReceived(CustomResourceEventSource.java:133)
        at io.javaoperatorsdk.operator.processing.event.internal.CustomResourceEventSource.eventReceived(CustomResourceEventSource.java:27)
        at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
        at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:145)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$TypedWatcherWebSocketListener.onMessage(WatchConnectionManager.java:83)
```

Maybe this is related to a null `objectMapper` (??) as I also got this new warning on Quarkus startup:

```
2021-06-09 11:45:41,884 WARN  [io.qua.arc.impl] (Quarkus Main Thread) 
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build
Removed beans:
        - PRODUCER_METHOD bean io.quarkus.jackson.runtime.ObjectMapperProducer#objectMapper() [types=[interface com.fasterxml.jackson.core.Versioned, interface java.io.Serializable, class com.fasterxml.jackson.core.ObjectCodec, class com.fasterxml.jackson.databind.ObjectMapper, class com.fasterxml.jackson.core.TreeCodec], qualifiers=[@javax.enterprise.inject.Default(), @javax.enterprise.inject.Any()]]
Required type: class com.fasterxml.jackson.databind.ObjectMapper
Required qualifiers: [@javax.enterprise.inject.Default()]
Solutions:
        - Application developers can eliminate false positives via the @Unremovable annotation
        - Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
        - See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
================================================================================
```

**Comment by lbroudoux** [comment]
Update on 2) above.

Actually, the NPE is related to the removed `objectMapper`. I just added 

```java
@Inject
   ObjectMapper objectMapper;
```

to my QuarkusApplication class and NPE disappeared. Don't know why `objectMapper` was not removed on previous version...

**Comment by metacosm** [comment]
Regarding 2), I've started seeing this recently as well, not sure why right now… Looking into it.
Regarding 1), if the operator needs to read the CRD (which is optional), it will need Cluster-level read access since CRDs are cluster-level resources. The SDK only needs that permission if you want to validate that the CRD exists before registering your controller with the cluster. This can be deactivated by adding `quarkus.operator-sdk.crd.validate=false` to your `application.properties`.

**Comment by lbroudoux** [comment]
Thanks for quick reply! As the operator is targeted to be installed via OLM, I think I can deactivate the CRD presence check.
