### ISSUE TITLE
java.lang.RuntimeException: Error injecting io.quarkus.arc.runtime.devconsole.InvocationsMonitor when stopping dev console

### ISSUE THREAD

**Issue by goldmann** [quarkiverse/quarkus-operator-sdk#69]
I'm seeing following stacktraces after hitting CTRL^C to shut down the dev console.

```
SLF4J: Failed toString() invocation on an object of type [com.redhat.agogos.k8s.event.RunEventSource_ClientProxy]
Reported exception:
java.lang.RuntimeException: Error injecting io.quarkus.arc.runtime.devconsole.InvocationsMonitor io.quarkus.arc.runtime.devconsole.InvocationInterceptor.invocationMonitor
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.create(InvocationInterceptor_Bean.zig:311)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.get(InvocationInterceptor_Bean.zig:392)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.get(InvocationInterceptor_Bean.zig:427)
        at com.redhat.agogos.k8s.event.RunEventSource_Subclass.<init>(RunEventSource_Subclass.zig:32)
        at com.redhat.agogos.k8s.event.RunEventSource_Bean.create(RunEventSource_Bean.zig:254)
        at com.redhat.agogos.k8s.event.RunEventSource_Bean.create(RunEventSource_Bean.zig:359)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
        at com.redhat.agogos.k8s.event.RunEventSource_ClientProxy.arc$delegate(RunEventSource_ClientProxy.zig:67)
        at com.redhat.agogos.k8s.event.RunEventSource_ClientProxy.toString(RunEventSource_ClientProxy.zig:226)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
        at org.slf4j.impl.Slf4jLogger.warn(Slf4jLogger.java:242)
        at io.javaoperatorsdk.operator.processing.event.DefaultEventSourceManager.close(DefaultEventSourceManager.java:61)
        at io.javaoperatorsdk.operator.Operator.close(Operator.java:66)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at io.quarkus.arc.runtime.devconsole.InvocationsMonitor_Bean.get(InvocationsMonitor_Bean.zig:144)
        at io.quarkus.arc.runtime.devconsole.InvocationsMonitor_Bean.get(InvocationsMonitor_Bean.zig:167)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.create(InvocationInterceptor_Bean.zig:294)
        ... 23 more
```

**Comment by goldmann** [comment]
quarkus-operator-sdk: `1.9.2`
java-operator-sdk: `1.9.0`
quarkus: `1.13.6.Final`

**Comment by metacosm** [comment]
From the stack trace this seems to be caused by the `RunEventSource.toString` method. It looks like it requires some external CDI dependency that cannot be found (probably because the app is being shut down). I'm not sure there's anything that can be done by the SDK. Note that this should only occur when debug-level is activated for logging.

**Comment by goldmann** [comment]
After I upgraded to java-operator-sdk `1.9.1` the issue disappeared. Probably this fixed it: https://github.com/java-operator-sdk/java-operator-sdk/commit/940b0cd6dd442a6b711241bc98551931d68a9ae7

**Comment by metacosm** [comment]
Thanks for letting us know!
