### ISSUE TITLE
When running in remote dev mode there are constantly logged RejectedExecutionException errors 

### ISSUE THREAD

**Issue by mswiderski** [quarkiverse/quarkus-operator-sdk#9]
When having a project with operator-sdk running in kubernetes cluster with quarkus remote dev mode there are lots of exception logged 

````
2021-03-16 10:21:26,713 WARN  [io.fab.kub.cli.dsl.int.WatcherWebSocketListener] (reconnectAttempt|Executor for Watch 1216778335) Exec Failure: java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:157)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:204)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:144)
	at okhttp3.RealCall.enqueue(RealCall.java:93)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:190)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:409)
	at io.fabric8.kubernetes.client.dsl.internal.WebSocketClientRunner.run(WebSocketClientRunner.java:38)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.runWatch(AbstractWatchManager.java:160)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener$1$1.execute(WatcherWebSocketListener.java:174)
	at io.fabric8.kubernetes.client.dsl.internal.NamedRunnable.run(NamedRunnable.java:39)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@7f1fcec7 rejected from java.util.concurrent.ThreadPoolExecutor@108b32cc[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:154)
	... 15 more
````

maybe even sources are not properly closed during application restarts and thus leaving some things behind.

**Comment by metacosm** [comment]
Yes, watchers are not properly closed at the moment, there's already an issue opened for this: https://github.com/java-operator-sdk/java-operator-sdk/issues/289

**Comment by mswiderski** [comment]
I have seen that issue so hopefully will address both issues. 

And speaking about life cycle of the operator, do you plan to have it automatically controlled by the extension? 

At the moment I am injecting `Operator` instance and call `start` on it by observing `StartupEvent` from Quarkus. But there is no `stop` method so can't be cleaned easily either. So wondering if that is how it should be or the live cycle management will be part of the operator sdk extension?

**Comment by metacosm** [comment]
I think this issue can be closed now, correct, @mswiderski?

**Comment by mswiderski** [comment]
I haven't tested this but feel free to close since it is assumed to be fixed. I will try to test it out in a week or so.

Thanks for fix (and letting me know)!

**Comment by metacosm** [comment]
Please re-open if you find that the issue is still occurring.
